name : PipelineWorkfLow

on:
  push:
     branches:
       - main
  pull_request :
     branches:
       - main

jobs:
   build:
       name: Azure Pipeline
       runs-on: ubantu-latest
       steps:
       - name: Azure Pipelines Actions
         user: Azure/pipelines@v1
         with:
           azure-devops-project-url: https://dev.azure.com/subhamintune/AglieProject
           azutr-pipeline-name: 'devops9861.Netapp'
           azure-devops=tocken: ${{ secrets.AZURE_DEVOPS_TOKEN }}